name: markdown_preview
description: A starting point for a command line/console program.
version: 1.0.0+1
publish_to: none

executable:
  markdown_preview:

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  args: ^2.3.0
  markdown: ^5.0.0
  mason_logger: ^0.1.0-dev.7
  meta: ^1.7.0
  path: ^1.8.1
  recase: ^4.0.0
  shelf: ^1.3.0
  shelf_static: ^1.1.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
